function daftarJST(param)
    % Buat figure form main menu
    % mainmenufh = figure('visible', 'off');
     daftarJSTfh = figure('MenuBar', 'none',...
         'Color', [0.941 0.941 0.941],...
         'NumberTitle', 'off',...
         'Name', 'Create JST',...
         'Position', [480,200,400,350],...
         'Resize', 'off',...
         'Visible','off');
    handlesparam=guidata(param);
    handles.mhs = handlesparam.mhs;
    handles.conn = handlesparam.conn;
    % Buat object eigen
    handles.eigen = handlesparam.eigen;
     
     
    % Panel form data
    handles.formph = uipanel(daftarJSTfh, 'Title', 'Form Create Jaringan Syaraf Tiruan',...
                                'Units', 'Pixels',...
                                'Position',[50 70 300 260]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'EPOCH : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 190 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'GOAL : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 150 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'MINGRAD : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 110 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'LEARNRATE : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 70 100 30]);  
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'TIME : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 30 100 30]);
	handles.editEpoch = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'String','1000',...
                                'Position', [130 195 150 30]);
	handles.editGoal = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'String','0',...
                                'Position', [130 155 150 30]);
	handles.editMinGrad = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'String','1e-5',...
                                'Position', [130 115 150 30]);
	handles.editLearnRate = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'String','0.01',...
                                'Position', [130 75 150 30]);
	handles.editTime = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'String','Inf',...
                                'Position', [130 35 150 30]);               
    % Buat button action
    uicontrol(daftarJSTfh, 'Style', 'Push Button',...
                                'String', 'Create & Train',...
                                'Position', [50 20 110 30],...
                                'FontName', 'Century Schoolbook',...
                                'FontSize', 10,...
                                'Enable', 'on',...
                                'Callback', @btnCreateTrainh_callback);
    uicontrol(daftarJSTfh, 'Style', 'Push Button',...
                                'String', 'Cancel',...
                                'Position', [240 20 110 30],...
                                'FontName', 'Century Schoolbook',...
                                'FontSize', 10,...
                                'Enable', 'on',...
                                'Callback', @btnCancelh_callback);
    set(daftarJSTfh, 'Visible', 'on');
    % save GUI Data
    guidata(gcf, handles);
end

function btnCreateTrainh_callback(~, ~)
    handles = guidata(gcf);
    jaringan = JST;
    target = jaringan.createTargetMatriks(handles.conn);
    jaringan.Create(handles.eigen.MatrikBobot, handles.mhs.getJumlahData(handles.conn), str2double(get(handles.editEpoch, 'String')),...
                    str2double(get(handles.editGoal, 'String')), str2double(get(handles.editMinGrad, 'String')),...
                    str2double(get(handles.editLearnRate, 'String')), str2double(get(handles.editTime, 'String')) );
	jaringan.Train(target);
    msgbox('Jaringan Syaraf Tiruan berhasil dibuat dan di training', 'Data');
end

function btnCancelh_callback(~, ~)
    delete(gcbf);
end