function mainMenu(varargin)
     % Buat figure form main menu
     mainmenufh = figure('MenuBar', 'none',...
         'Color', [0.941 0.941 0.941],...
         'Visible', 'on',...
         'NumberTitle', 'off',...
         'Name', 'Frendface - Simulation System Face Recognition and Detection',...
         'Position', [280,130,800,500],...
         'Resize', 'off',...
         'Visible', 'off',...
         'CloseRequestFcn',@mainMenu_CloseRequestFcn);
     
    %javax.swing.UIManager.setLookAndFeel('com.sun.java.swing.plaf.motif.MotifLookAndFeel');
    %javax.swing.UIManager.setLookAndFeel('javax.swing.plaf.metal.MetalLookAndFeel');
    javax.swing.UIManager.setLookAndFeel('com.jgoodies.looks.plastic.Plastic3DLookAndFeel');
    %javax.swing.UIManager.setLookAndFeel('OceanTheme');
    %javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getLookAndFeel());
    
    % Buat button main menu
    btnMainMenu(mainmenufh);
    
    % Buat static text
    uicontrol(mainmenufh, 'Style', 'text',...
                            'String', 'SELAMAT DATANG DI PROGRAM SIMULASI SISTEM ABSENSI DENGAN PENGENALAN WAJAH',...
                            'FontName', 'Century Schoolbook',...
                            'FontSize', 20,...
                            'FontWeight', 'bold',...
                            'Position',[150 180 500 100]);            
                
    uicontrol(mainmenufh, 'Style', 'text',...
                            'String', '© 2012 Final Project Created By Frendy Priandi (2009130009)',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'Position',[400 0 400 20]);
    %inspect(mainmenufh);
    %propedit(mainmenufh);
    
    % Set figure center position
    % movegui(mainmenufh, 'center');
    % Set figure visible
    set(mainmenufh, 'Visible', 'on');
end

% Function membuat button main menu
function btnMainMenu(currentfig)
    btnPendaftaranh = uicontrol(currentfig, 'Style', 'Push Button',...
                                'String', 'Pendaftaran',...
                                'Position', [100 440 120 60],...
                                'FontName', 'Century Schoolbook',...
                                'FontSize', 10);
    set(btnPendaftaranh, 'Callback', @btnPendaftaranh_callback);
    btnCatatKehadiranh = uicontrol(currentfig, 'Style', 'Push Button',...
                                    'String', 'Catat Kehadiran',...
                                    'Position', [220 440 120 60],...
                                    'FontName', 'Century Schoolbook',...
                                    'FontSize', 10);                        
    set(btnCatatKehadiranh, 'Callback', @btnCatatKehadiranh_callback);         
    btnDatabaseWajahh = uicontrol(currentfig, 'Style', 'Push Button',...
                                    'String', 'Database Wajah',...
                                    'Position', [340 440 120 60],...
                                    'FontName', 'Century Schoolbook',...
                                    'FontSize', 10);
    set(btnDatabaseWajahh, 'Callback', @btnDatabaseWajahh_callback);
    btnDaftarKehadiranh = uicontrol(currentfig, 'Style', 'Push Button',...
                                    'String', 'Daftar Kehadiran',...
                                    'Position', [460 440 120 60],...
                                    'FontName', 'Century Schoolbook',...
                                    'FontSize', 10);
    set(btnDaftarKehadiranh, 'Callback', @btnDaftarKehadiranh_callback);
    btnKeluarh = uicontrol(currentfig, 'Style', 'Push Button',...
                            'String', 'Keluar',...
                            'Position', [580 440 120 60],...
                            'FontName', 'Century Schoolbook',...
                            'FontSize', 10);
    set(btnKeluarh, 'Callback', @btnKeluarh_callback);      
end

% Dieksekusi ketika tombol pendaftaran ditekan
function btnPendaftaranh_callback(~, ~)
    % Buat figure form pendaftaran
    % pendaftaranfh = figure;
    delete(gcbf);
    pendaftaran;
end

% Dieksekusi ketika tombol catat kehadiran ditekan
function btnCatatKehadiranh_callback(~, ~)
    % Buat figure form catat kehadiran
    delete(gcbf);
    catatKehadiran;
end

% Dieksekusi ketika tombol database wajah ditekan
function btnDatabaseWajahh_callback(~, ~)
    % Buat figure form database wajah
    delete(gcbf);
    databaseWajah;
end

% Dieksekusi ketika tombol daftar kehadiran ditekan
function btnDaftarKehadiranh_callback(~, ~)
    % Buat figure form daftar kehadiran
    delete(gcbf);
    daftarKehadiran;
end

% Dieksekusi ketika tombol exit ditekan
function btnKeluarh_callback(~, ~)
    close(gcbf);
end

% Dijalankan ketika figure diclose
function mainMenu_CloseRequestFcn(~, ~)
% hObject    handle to myCameraGUI (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: delete(hObject) closes the figure
    selection = questdlg(['Close ' get(gcbf,'Name') '?'],...
                ['Close ' get(gcbf,'Name') '...'],...
                'Yes','No','Yes');
    if strcmp(selection,'No')
        return;
    end
    delete(gcbf);
end