function saveData(param)
%SAVEDATA Summary of this function goes here
%   Detailed explanation goes here
    handlesparam=guidata(param);
    saveDatafh = figure('MenuBar', 'none',...
         'Color', [0.941 0.941 0.941],...
         'NumberTitle', 'off',...
         'Name', 'Pendaftaran',...
         'Position', [370,200,600,350],...
         'Resize', 'off',...
         'WindowStyle', 'modal',...
         'Visible','off',...
         'CloseRequestFcn',@saveDatafh_CloseRequestFcn);
    % Panel form data
    handles.formph = uipanel(saveDatafh, 'Title', 'Form Isi Data',...
                                'Units', 'Pixels',...
                                'Position',[20 20 300 270]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'NPM : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 210 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'PASSWORD : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 170 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'NAMA : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 130 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'ALAMAT : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 90 100 30]);  
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'TELEPON : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 50 100 30]);
    uicontrol(handles.formph, 'Style', 'text',...
                            'String', 'EMAIL : ',...
                            'FontName', 'Times New Roman',...
                            'FontSize', 12,...
                            'HorizontalAlignment', 'left',...
                            'Position',[20 10 100 30]);
	handles.editNPM = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'Position', [130 215 150 30]);
	handles.editPassword = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'Position', [130 175 150 30]);
	handles.editNama = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'Position', [130 135 150 30]);
	handles.editAlamat = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'Position', [130 95 150 30]);
	handles.editTelepon = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'Position', [130 55 150 30]);
	handles.editEmail = uicontrol(handles.formph, 'Style', 'edit',...
                                'BackgroundColor', 'white',...
                                'Position', [130 15 150 30]);
	
	% Panel current user data listbox
    handles.listboxph = uipanel(saveDatafh, 'Title', 'List Current Data',...
                                'Units', 'Pixels',...
                                'Position',[20 20 300 270],...
                                'Visible', 'off');

                                        
    % Panel preview picture
    previewph = uipanel(saveDatafh, 'Title', 'Preview',...
                                'Units', 'Pixels',...
                                'Position',[350 80 220 220]);
    % Buat preview axes
    axes('Parent', previewph,...
                    'Box', 'on',...
                    'Units', 'Pixels',...
                    'Position', [13 10 190 190],...
                    'XTickMode','manual', 'YTickMode','manual', ...
                    'XTick',[], 'YTick',[], 'XTickLabelMode', 'manual', ...
                    'XTickLabel', [], 'YTickLabelMode', 'manual', 'YTickLabel', []);
    imshow(imresize(handlesparam.image(:,:,:,1), [190 190]));
                
    % Button save picture
    handles.btnSavePicture = uicontrol(saveDatafh, 'Style', 'Push Button',...
                                    'String', 'Save',...
                                    'Position', [400 20 110 30],...
                                    'FontName', 'Times New Roman',...
                                    'FontSize', 12,...
                                    'Callback', {@btnSavePicture_callback, handlesparam});
    % Create the button group.
    handles.groupButton = uibuttongroup(saveDatafh, 'Title', 'Pilihan',...
                                'Units', 'pixels',...
                                'Position', [20 300 300 50],...
                                'SelectionChangeFcn',@selcbk);
    uicontrol('Style','Radio','String','New User Data',...
        'pos',[10 15 120 10],'parent',handles.groupButton,'HandleVisibility','off');
    uicontrol('Style','Radio','String','Current User Data',...
        'pos',[150 15 120 10],'parent',handles.groupButton,'HandleVisibility','off');

                
    set(saveDatafh, 'Visible', 'on');
    %inspect(rbNew);
    % variable for save data frame by frame
    handles.current_frame = 1;
    % Make a new connection
    handles.conn = database('tgsakhir','root','','MySQL','jdbc:mysql://localhost:3306/');
    % Save to current figure
    guidata(gcf, handles);
end

function selcbk(hObject,~)
    handles=guidata(gcf);
    if (strcmp(get(get(hObject,'SelectedObject'), 'String'), 'New User Data'))
        set(handles.listboxph, 'Visible', 'off');
        set(handles.formph, 'Visible', 'on');
    else
        set(handles.formph, 'Visible', 'off');
        
        conn = database('tgsakhir','root','','MySQL','jdbc:mysql://localhost:3306/');
        curs = exec(conn, 'select NPM, Nama from mahasiswa order by NPM');
        setdbprefs('DataReturnFormat','cellarray');
        curs = fetch(curs);
        handles.listboxdata = get(curs, 'Data');
        for i=1:rows(curs)
            handles.listboxdata{i,3} = [handles.listboxdata{i, 1} ' - ' handles.listboxdata{i, 2}]; 
        end
        


        handles.listBox = uicontrol(handles.listboxph,'Style','listbox',...
                                    'String',handles.listboxdata(:,3),...
                                    'Position',[10 10 280 230],...
                                    'Value', 1);
        % Save to current figure
        guidata(gcf, handles);
        set(handles.listboxph, 'Visible', 'on');
    end
end

function btnSavePicture_callback(~, ~, handlesparam)
    handles=guidata(gcf);
    % Make new object mahasiswa
    mhs = Mahasiswa;
    if (strcmp(get(get(handles.groupButton,'SelectedObject'), 'String'), 'New User Data'))
        if (isempty(get(handles.editNPM, 'String')))
            errordlg('NPM harus diisi', 'NPM'); 
        else
            try
                [file_name, path_name] = saveDialogBox(['Save Image Frame 1 to ' num2str(handlesparam.vid.FramesAcquired)]);
                file_name = findTypeFile(file_name);
                if (file_name ~= 0)
                    % Input data to object mhs
                    mhs.setNPM(get(handles.editNPM, 'String'));
                    mhs.setPassword(get(handles.editPassword, 'String'));
                    mhs.setNama(get(handles.editNama, 'String'));
                    mhs.setAlamat(get(handles.editAlamat, 'String'));
                    mhs.setTelepon(get(handles.editTelepon, 'String'));
                    mhs.setEmail(get(handles.editEmail, 'String'));
                    % Save data mahasiswa
                    mhs.save(handles.conn);
                    % Save data image mahasiswa
                    mhs.saveAllCitra(handles.conn, handlesparam.vid.FramesAcquired, handlesparam.image, path_name, file_name);
                    msgbox('Data Telah Tersimpan', 'Save');
                end
            catch exception
                errordlg('Data Gagal Disimpan', 'Data');
                throw(exception);
            end
        end
    else
        [file_name, path_name] = saveDialogBox(['Save Image Frame ' num2str(handles.current_frame)]);
        file_name = findTypeFile(file_name);
        if (file_name ~= 0)
            try                
                mhs.setNPM(handles.listboxdata{get(handles.listBox, 'value'), 1});
                
                % Update data and image mahasiswa
                mhs.updateData(handles.conn, handlesparam.image, handles.current_frame, path_name, file_name);

                handles.current_frame=handles.current_frame+1;
                if (handles.current_frame>handlesparam.vid.FramesAcquired)
                    set(handles.btnSavePicture, 'Enable', 'off');
                else
                    imshow(imresize(handlesparam.image(:,:,:,handles.current_frame), [190 190]));
                end  
                % Save to current figure
                guidata(gcf, handles);                
                
                msgbox('Data Telah Tersimpan', 'Save');
            catch exception
                errordlg('Data Gagal Disimpan', 'Data');
                throw(exception);
            end
        end
    end
    clear mhs;
end

function ret = findTypeFile(file_name)
    if (strfind(file_name, '.'))
        idx=strfind(file_name, '.');
        for i=1:4
            file_name(idx) = '';
        end
    end
    ret = file_name;
end

function [file_name, path_name] = saveDialogBox(title_name)
        [file_name, path_name] = uiputfile({'*.jpg;*.bmp;*.tif;*.png;*.gif','All Image Files';...
          '*.*','All Files' },title_name,...
          'C:\Work\newfile.bmp');
end

function saveDatafh_CloseRequestFcn(~, ~)
    delete(gcbf);
end